/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MiniProject;

/**
 *
 * @author ASUS
 */
public class UserOptions extends javax.swing.JFrame {

    /**
     * Creates new form UserOptions
     */
    public UserOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModeUser = new javax.swing.JPanel();
        CheckStatusB = new javax.swing.JButton();
        NewLicenseB = new javax.swing.JButton();
        RenewLicenseB = new javax.swing.JButton();
        RenewLicenseB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModeUser.setBackground(new java.awt.Color(255, 255, 255));
        ModeUser.setPreferredSize(new java.awt.Dimension(1920, 1080));

        CheckStatusB.setBackground(new java.awt.Color(204, 204, 204));
        CheckStatusB.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        CheckStatusB.setText("Check Status");
        CheckStatusB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CheckStatusB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStatusBActionPerformed(evt);
            }
        });

        NewLicenseB.setBackground(new java.awt.Color(204, 204, 204));
        NewLicenseB.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        NewLicenseB.setText("Apply for New Licence");
        NewLicenseB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NewLicenseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewLicenseBActionPerformed(evt);
            }
        });

        RenewLicenseB.setBackground(new java.awt.Color(204, 204, 204));
        RenewLicenseB.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        RenewLicenseB.setText("Payments");
        RenewLicenseB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RenewLicenseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewLicenseBActionPerformed(evt);
            }
        });

        RenewLicenseB1.setBackground(new java.awt.Color(204, 204, 204));
        RenewLicenseB1.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        RenewLicenseB1.setText("Renew License");
        RenewLicenseB1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RenewLicenseB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RenewLicenseB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModeUserLayout = new javax.swing.GroupLayout(ModeUser);
        ModeUser.setLayout(ModeUserLayout);
        ModeUserLayout.setHorizontalGroup(
            ModeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModeUserLayout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addGroup(ModeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RenewLicenseB, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ModeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CheckStatusB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NewLicenseB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RenewLicenseB1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(771, Short.MAX_VALUE))
        );
        ModeUserLayout.setVerticalGroup(
            ModeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModeUserLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(CheckStatusB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(NewLicenseB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(RenewLicenseB1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(RenewLicenseB, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(384, Short.MAX_VALUE))
        );

        getContentPane().add(ModeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1910, 1070));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckStatusBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStatusBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckStatusBActionPerformed

    private void NewLicenseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewLicenseBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewLicenseBActionPerformed

    private void RenewLicenseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewLicenseBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RenewLicenseBActionPerformed

    private void RenewLicenseB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RenewLicenseB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RenewLicenseB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckStatusB;
    private javax.swing.JPanel ModeUser;
    private javax.swing.JButton NewLicenseB;
    private javax.swing.JButton RenewLicenseB;
    private javax.swing.JButton RenewLicenseB1;
    // End of variables declaration//GEN-END:variables
}
